version: "3.8"
services:
  api:
    build:
      context: .
    container_name: api
    ports:
      - '8000:8000'
    restart: no
    depends_on:
      postgres:
        condition: service_started
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
     - db:/var/lib/postgresql/data
volumes:
  db: 
